<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Åland Islands', 'code' => 'AX', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Albania', 'code' => 'AL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Algeria', 'code' => 'DZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'American Samoa', 'code' => 'AS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Andorra', 'code' => 'AD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Angola', 'code' => 'AO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Anguilla', 'code' => 'AI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Antarctica', 'code' => 'AQ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Argentina', 'code' => 'AR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Armenia', 'code' => 'AM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Aruba', 'code' => 'AW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Australia', 'code' => 'AU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Austria', 'code' => 'AT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bahamas', 'code' => 'BS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bahrain', 'code' => 'BH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bangladesh', 'code' => 'BD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Barbados', 'code' => 'BB', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Belarus', 'code' => 'BY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Belgium', 'code' => 'BE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Belize', 'code' => 'BZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Benin', 'code' => 'BJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bermuda', 'code' => 'BM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bhutan', 'code' => 'BT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Botswana', 'code' => 'BW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Brazil', 'code' => 'BR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Bulgaria', 'code' => 'BG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Burundi', 'code' => 'BI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Cambodia', 'code' => 'KH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Cameroon', 'code' => 'CM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Canada', 'code' => 'CA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Cape Verde', 'code' => 'CV', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Central African Republic', 'code' => 'CF', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Chad', 'code' => 'TD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Chile', 'code' => 'CL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'China', 'code' => 'CN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Christmas Island', 'code' => 'CX', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Colombia', 'code' => 'CO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Comoros', 'code' => 'KM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Congo', 'code' => 'CG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Cook Islands', 'code' => 'CK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Costa Rica', 'code' => 'CR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Croatia', 'code' => 'HR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Cuba', 'code' => 'CU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Curaçao', 'code' => 'CW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Cyprus', 'code' => 'CY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Denmark', 'code' => 'DK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Djibouti', 'code' => 'DJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Dominica', 'code' => 'DM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Ecuador', 'code' => 'EC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Egypt', 'code' => 'EG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'El Salvador', 'code' => 'SV', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Eritrea', 'code' => 'ER', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Estonia', 'code' => 'EE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Ethiopia', 'code' => 'ET', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Fiji', 'code' => 'FJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Finland', 'code' => 'FI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'France', 'code' => 'FR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'French Guiana', 'code' => 'GF', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'French Polynesia', 'code' => 'PF', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Gabon', 'code' => 'GA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Gambia', 'code' => 'GM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Georgia', 'code' => 'GE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Germany', 'code' => 'DE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Ghana', 'code' => 'GH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Gibraltar', 'code' => 'GI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Greece', 'code' => 'GR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Greenland', 'code' => 'GL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Grenada', 'code' => 'GD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Guam', 'code' => 'GU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Guatemala', 'code' => 'GT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Guernsey', 'code' => 'GG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Guinea', 'code' => 'GN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Guyana', 'code' => 'GY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Haiti', 'code' => 'HT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Honduras', 'code' => 'HN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Hong Kong', 'code' => 'HK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Hungary', 'code' => 'HU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Iceland', 'code' => 'IS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'India', 'code' => 'IN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Indonesia', 'code' => 'ID', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Iraq', 'code' => 'IQ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Ireland', 'code' => 'IE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Isle of Man', 'code' => 'IM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Israel', 'code' => 'IL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Italy', 'code' => 'IT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Jamaica', 'code' => 'JM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Japan', 'code' => 'JP', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Jersey', 'code' => 'JE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Jordan', 'code' => 'JO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Kenya', 'code' => 'KE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Kiribati', 'code' => 'KI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Korea, Republic of', 'code' => 'KR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Kuwait', 'code' => 'KW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Latvia', 'code' => 'LV', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Lebanon', 'code' => 'LB', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Lesotho', 'code' => 'LS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Liberia', 'code' => 'LR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Libya', 'code' => 'LY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Lithuania', 'code' => 'LT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Luxembourg', 'code' => 'LU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Macao', 'code' => 'MO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Madagascar', 'code' => 'MG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Malawi', 'code' => 'MW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Malaysia', 'code' => 'MY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Maldives', 'code' => 'MV', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Mali', 'code' => 'ML', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Malta', 'code' => 'MT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Martinique', 'code' => 'MQ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Mauritania', 'code' => 'MR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Mauritius', 'code' => 'MU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Mayotte', 'code' => 'YT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Mexico', 'code' => 'MX', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Moldova, Republic of', 'code' => 'MD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Monaco', 'code' => 'MC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Mongolia', 'code' => 'MN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Montenegro', 'code' => 'ME', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Montserrat', 'code' => 'MS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Morocco', 'code' => 'MA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Mozambique', 'code' => 'MZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Myanmar', 'code' => 'MM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Namibia', 'code' => 'NA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Nauru', 'code' => 'NR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Nepal', 'code' => 'NP', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Netherlands', 'code' => 'NL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'New Caledonia', 'code' => 'NC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'New Zealand', 'code' => 'NZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Nicaragua', 'code' => 'NI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Niger', 'code' => 'NE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Nigeria', 'code' => 'NG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Niue', 'code' => 'NU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Norway', 'code' => 'NO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Oman', 'code' => 'OM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Pakistan', 'code' => 'PK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Palau', 'code' => 'PW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Palestine, State of', 'code' => 'PS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Panama', 'code' => 'PA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Paraguay', 'code' => 'PY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Peru', 'code' => 'PE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Philippines', 'code' => 'PH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Pitcairn', 'code' => 'PN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Poland', 'code' => 'PL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Portugal', 'code' => 'PT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Qatar', 'code' => 'QA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Réunion', 'code' => 'RE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Romania', 'code' => 'RO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Russian Federation', 'code' => 'RU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Rwanda', 'code' => 'RW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Saint Barthélemy', 'code' => 'BL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Saint Martin (French part)', 'code' => 'MF', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Samoa', 'code' => 'WS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'San Marino', 'code' => 'SM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Senegal', 'code' => 'SN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Serbia', 'code' => 'RS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Seychelles', 'code' => 'SC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Singapore', 'code' => 'SG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Slovakia', 'code' => 'SK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Slovenia', 'code' => 'SI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Somalia', 'code' => 'SO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'South Africa', 'code' => 'ZA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'South Sudan', 'code' => 'SS', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Spain', 'code' => 'ES', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Sudan', 'code' => 'SD', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Suriname', 'code' => 'SR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Swaziland', 'code' => 'SZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Sweden', 'code' => 'SE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Switzerland', 'code' => 'CH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Taiwan', 'code' => 'TW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Thailand', 'code' => 'TH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Togo', 'code' => 'TG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Tokelau', 'code' => 'TK', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Tonga', 'code' => 'TO', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Tunisia', 'code' => 'TN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Turkey', 'code' => 'TR', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Tuvalu', 'code' => 'TV', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Uganda', 'code' => 'UG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Ukraine', 'code' => 'UA', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'United Kingdom', 'code' => 'GB', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'United States', 'code' => 'US', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Uruguay', 'code' => 'UY', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Vanuatu', 'code' => 'VU', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Viet Nam', 'code' => 'VN', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Virgin Islands, British', 'code' => 'VG', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Western Sahara', 'code' => 'EH', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Yemen', 'code' => 'YE', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Zambia', 'code' => 'ZM', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
        ];
        DB::table('countries')->insert($data);
    }
}
