<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class PlayersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [
            /* CSK TEAM */
            [
                'team_id' => '1',
                'first_name' => 'Mahendra',
                'middle_name' => 'Singh',
                'last_name' => 'Dhoni',
                'short_name' => 'MS Dhoni',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '2',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '4',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'KM',
                'middle_name' => null,
                'last_name' => 'Asif',
                'short_name' => 'KM Asif',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'Sam',
                'middle_name' => null,
                'last_name' => 'Billings',
                'short_name' => 'S Billings',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '3',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '3',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'Chaitanya',
                'middle_name' => null,
                'last_name' => 'Bishnoi',
                'short_name' => 'C Bishnoi',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'Deepak',
                'middle_name' => null,
                'last_name' => 'Chahar',
                'short_name' => 'D Chahar',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '9',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'Faf',
                'middle_name' => 'du',
                'last_name' => 'Plessis',
                'short_name' => 'du Plessis',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '1',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'Harbhajan',
                'middle_name' => null,
                'last_name' => 'Singh',
                'short_name' => 'H Singh',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'Imran',
                'middle_name' => null,
                'last_name' => 'Tahir',
                'short_name' => 'I Tahir',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'Ravindra',
                'middle_name' => null,
                'last_name' => 'Jadeja',
                'short_name' => 'R Jadeja',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'Kedar',
                'middle_name' => null,
                'last_name' => 'Jadhav',
                'short_name' => 'K Jadhav',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '1',
                'first_name' => 'Suresh',
                'middle_name' => null,
                'last_name' => 'Raina',
                'short_name' => 'S Raina',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '2',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],



            /* KXIP TEAM */
            [
                'team_id' => '2',
                'first_name' => 'Ravichandran',
                'middle_name' => null,
                'last_name' => 'Ashwin',
                'short_name' => 'R Ashwin',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '1',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '4',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'KM',
                'middle_name' => null,
                'last_name' => 'Asif',
                'short_name' => 'KM Asif',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'Moises',
                'middle_name' => null,
                'last_name' => 'Henriques',
                'short_name' => 'M Henriques',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '3',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'Sam',
                'middle_name' => null,
                'last_name' => 'Curran',
                'short_name' => 'S Curran',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'Andrew',
                'middle_name' => null,
                'last_name' => 'Tye',
                'short_name' => 'A Tye',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '9',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'Chris',
                'middle_name' => 'du',
                'last_name' => 'Gayle',
                'short_name' => 'C Gayle',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '1',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'Mujeeb Ur Rahman',
                'middle_name' => null,
                'last_name' => 'Rahman',
                'short_name' => 'Rahman',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'Mohammed',
                'middle_name' => null,
                'last_name' => 'Shami',
                'short_name' => 'M Shami',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'Nicholas',
                'middle_name' => null,
                'last_name' => 'Pooran',
                'short_name' => 'N Pooran',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '3',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'David',
                'middle_name' => null,
                'last_name' => 'Miller',
                'short_name' => 'D Miller',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '2',
                'first_name' => 'Lokesh',
                'middle_name' => null,
                'last_name' => 'Rahul',
                'short_name' => 'L Rahul',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '2',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],



            /* RCB TEAM */
            [
                'team_id' => '3',
                'first_name' => 'Virat',
                'middle_name' => null,
                'last_name' => 'Kohli',
                'short_name' => 'V Kohli',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '1',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '4',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'Akshdeep',
                'middle_name' => null,
                'last_name' => 'Nath',
                'short_name' => 'A Nath',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'Moeen',
                'middle_name' => null,
                'last_name' => 'Ali',
                'short_name' => 'Ali',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '3',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'Yuzvendra Chahal',
                'middle_name' => null,
                'last_name' => 'Chahal',
                'short_name' => 'Y Chahal',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'Nathan',
                'middle_name' => null,
                'last_name' => 'Coulter-Nile',
                'short_name' => 'Coulter-Nile',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '9',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'Colin',
                'middle_name' => 'de',
                'last_name' => 'Grandhomme',
                'short_name' => 'de Grandhomme',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '1',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'Tim',
                'middle_name' => null,
                'last_name' => 'Southee',
                'short_name' => 'T Southee',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'Umesh',
                'middle_name' => null,
                'last_name' => 'Yadav',
                'short_name' => 'Yadav',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'Marcus',
                'middle_name' => null,
                'last_name' => 'Stoinis',
                'short_name' => 'Stoinis',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'Parthiv',
                'middle_name' => null,
                'last_name' => 'Patel',
                'short_name' => 'P Patel',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '3',
                'first_name' => 'AB',
                'middle_name' => null,
                'last_name' => 'de Villiers',
                'short_name' => 'de Villiers',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '3',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '2',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],



            /* MI TEAM */
            [
                'team_id' => '4',
                'first_name' => 'Rohit',
                'middle_name' => null,
                'last_name' => 'Sharma',
                'short_name' => 'R Sharma',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '1',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '1',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Quinton',
                'middle_name' => null,
                'last_name' => 'de Kock',
                'short_name' => 'de Kock',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '3',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '2',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Yuvraj',
                'middle_name' => null,
                'last_name' => 'Singh',
                'short_name' => 'Y Singh',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '3',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Hardik',
                'middle_name' => null,
                'last_name' => 'Pandya',
                'short_name' => 'H Pandya',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '4',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Kieron',
                'middle_name' => null,
                'last_name' => 'Pollard',
                'short_name' => 'K Pollard',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Evin',
                'middle_name' => null,
                'last_name' => 'Lewis',
                'short_name' => 'E Lewis',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Krunal',
                'middle_name' => null,
                'last_name' => 'Pandya',
                'short_name' => 'K Pandya',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Mitchell McClenaghan',
                'middle_name' => null,
                'last_name' => 'McClenaghan',
                'short_name' => 'M McClenaghan',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Adam',
                'middle_name' => null,
                'last_name' => 'Milne',
                'short_name' => 'A Milne',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '9',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Lasith',
                'middle_name' => null,
                'last_name' => 'Malinga',
                'short_name' => 'L Malinga',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '4',
                'first_name' => 'Jasprit',
                'middle_name' => null,
                'last_name' => 'Bumrah',
                'short_name' => 'Bumrah',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],



            /* RR TEAM */
            [
                'team_id' => '5',
                'first_name' => 'Steven',
                'middle_name' => null,
                'last_name' => 'Smith',
                'short_name' => 'S Smith',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '1',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '1',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Aryaman',
                'middle_name' => null,
                'last_name' => 'Birla',
                'short_name' => 'A Birla',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '2',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Jos',
                'middle_name' => null,
                'last_name' => 'Buttler',
                'short_name' => 'Buttler',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '3',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '3',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Ajinkya',
                'middle_name' => null,
                'last_name' => 'Rahane',
                'short_name' => 'A Rahane',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '4',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Ben',
                'middle_name' => null,
                'last_name' => 'Stokes',
                'short_name' => 'Stokes',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Ashton',
                'middle_name' => null,
                'last_name' => 'Turner',
                'short_name' => 'A Turner',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Oshane',
                'middle_name' => null,
                'last_name' => 'Thomas',
                'short_name' => 'O Thomas',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Ish',
                'middle_name' => null,
                'last_name' => 'Sodhi',
                'short_name' => 'I Sodhi',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Liam',
                'middle_name' => null,
                'last_name' => 'Livingstone',
                'short_name' => 'Livingstone',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '9',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Dhawal',
                'middle_name' => null,
                'last_name' => 'Kulkarni',
                'short_name' => 'D Kulkarni',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '5',
                'first_name' => 'Jaydev',
                'middle_name' => null,
                'last_name' => 'Unadkat',
                'short_name' => 'Unadkat',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '2',
                'batting_order' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],



            /* KKR TEAM */
            [
                'team_id' => '6',
                'first_name' => 'Dinesh',
                'middle_name' => null,
                'last_name' => 'Karthik',
                'short_name' => 'D Karthik',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '2',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '1',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Carlos',
                'middle_name' => null,
                'last_name' => 'Brathwaite',
                'short_name' => 'Brathwaite',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '2',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Piyush',
                'middle_name' => null,
                'last_name' => 'Chawla',
                'short_name' => 'P Chawla',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '3',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Joe',
                'middle_name' => null,
                'last_name' => 'Denly',
                'short_name' => 'J Denly',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '4',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Chris',
                'middle_name' => null,
                'last_name' => 'Lynn',
                'short_name' => 'Lynn',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '2',
                'batting_order' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Shrikant',
                'middle_name' => null,
                'last_name' => 'Mundhe',
                'short_name' => 'S Mundhe',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Kamlesh',
                'middle_name' => null,
                'last_name' => 'Nagarkoti',
                'short_name' => 'K Nagarkoti',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Harry',
                'middle_name' => null,
                'last_name' => 'Gurney',
                'short_name' => 'H Gurney',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '2',
                'batting_order' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Lockie',
                'middle_name' => null,
                'last_name' => 'Ferguson',
                'short_name' => 'Ferguson',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '9',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Kuldeep',
                'middle_name' => null,
                'last_name' => 'Yadav',
                'short_name' => 'K Yadav',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '6',
                'first_name' => 'Sunil',
                'middle_name' => null,
                'last_name' => 'Narine',
                'short_name' => 'S Narine',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],



            /* DK TEAM */
            [
                'team_id' => '7',
                'first_name' => 'Colin',
                'middle_name' => null,
                'last_name' => 'Ingram',
                'short_name' => 'C Ingram',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '1',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Shikhar',
                'middle_name' => null,
                'last_name' => 'Dhawan',
                'short_name' => 'S Dhawan',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '1',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '2',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Manjot',
                'middle_name' => null,
                'last_name' => 'Kalra',
                'short_name' => 'M Kalra',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '3',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Colin',
                'middle_name' => null,
                'last_name' => 'Munro',
                'short_name' => 'C Munro',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '4',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Rishabh',
                'middle_name' => null,
                'last_name' => 'Pant',
                'short_name' => 'R Pant',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '3',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Keemo',
                'middle_name' => null,
                'last_name' => 'Paul',
                'short_name' => 'K Paul',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Kagiso',
                'middle_name' => null,
                'last_name' => 'Rabada',
                'short_name' => 'K Rabada',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Rahul',
                'middle_name' => null,
                'last_name' => 'Tewatia',
                'short_name' => 'R Tewatia',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Ishant',
                'middle_name' => null,
                'last_name' => 'Sharma',
                'short_name' => 'I Sharma',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '9',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Nathu',
                'middle_name' => null,
                'last_name' => 'Singh',
                'short_name' => 'N Singh',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '7',
                'first_name' => 'Jayant',
                'middle_name' => null,
                'last_name' => 'Yadav',
                'short_name' => 'S Narine',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],



            /* SH TEAM */
            [
                'team_id' => '8',
                'first_name' => 'David',
                'middle_name' => null,
                'last_name' => 'Warner',
                'short_name' => 'd Warner',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '1',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Kane',
                'middle_name' => null,
                'last_name' => 'Williamson',
                'short_name' => 'K Williamson',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '1',
                'batting_style_id' => '2',
                'bowling_style_id' => '1',
                'batting_order' => '2',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Shakib',
                'middle_name' => null,
                'last_name' => 'Al Hasan',
                'short_name' => 'S Al Hasan',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '2',
                'bowling_style_id' => '2',
                'batting_order' => '3',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Martin',
                'middle_name' => null,
                'last_name' => 'Guptill',
                'short_name' => 'M Guptill',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '5',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '4',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Jonny',
                'middle_name' => null,
                'last_name' => 'Bairstow',
                'short_name' => 'J Bairstow',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '3',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '5',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Deepak',
                'middle_name' => null,
                'last_name' => 'Hooda',
                'short_name' => 'D Hooda',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '6',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Siddarth',
                'middle_name' => null,
                'last_name' => 'Kaul',
                'short_name' => 'S Kaul',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '7',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Mohammad',
                'middle_name' => null,
                'last_name' => 'Nabi',
                'short_name' => 'M Nabi',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '7',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '8',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Shahbaz',
                'middle_name' => null,
                'last_name' => 'Nadeem',
                'short_name' => 'S Nadeem',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '2',
                'batting_order' => '9',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Yusuf',
                'middle_name' => null,
                'last_name' => 'Pathan',
                'short_name' => 'Y Pathan',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '1',
                'batting_order' => '10',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
            [
                'team_id' => '8',
                'first_name' => 'Rashid',
                'middle_name' => null,
                'last_name' => 'Khan',
                'short_name' => 'R Khan',
                'birth_date' => '1990-01-01',
                'birth_country_id' => '103',
                'playing_role_id' => '6',
                'batting_style_id' => '1',
                'bowling_style_id' => '2',
                'batting_order' => '11',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s')
            ],
        ];
        DB::table('players')->insert($data);
    }
}
